
server:
  # eureka-server服务的端口号
  port: 7001

spring:
  application:
    # 服务名称，集群中的每个实例的服务名称是相同的
    name: msc-eureka-server

# spring-cloud-starter-netflix-eureka-server依赖中既有eureka-server，也有eureka-client，
# 就是说msc-eureka-server项目既是eureka-server，也是eureka-client

eureka:
  instance:
    # eureka服务端的实例名称，本地开发时需要在host文件中将 eureka01 映射到 127.0.0.1
    hostname: eureka01
    # 优先使用ip
    prefer-ip-address: true
    # 租期，即心跳，当前client每隔这个时间会主动向server发起一次心跳，表明当前服务仍正常存活，单位秒
    # eureka server配置这个属性是为了后面做集群
    lease-renewal-interval-in-seconds: 2
    # server监听的某个client A 如果距离上次心跳时间超过 lease-expiration-duration-in-seconds 后仍未监听到 A 的心跳，
    # 则认为 A 挂掉了，并将其从正常实例中剔除，单位秒
    lease-expiration-duration-in-seconds: 6
  client:
    # 表示是否向(别的)注册中心注册自己
    register-with-eureka: false
    # client端是否去server端拉取注册实例信息，在这里是server端，所以配置false
    fetch-registry: false
  server:
    # 自我保护机制开启，该模式被激活后，它不会从注册列表中剔除因长时间没收到心跳导致租期过期的服务，
    # 而是等待修复，直到心跳恢复正常之后，它自动退出自我保护模式。
    enable-self-preservation: true
    # 自我保护机制开启的阈值，
    # 如果在15分钟内超过（100% - 85%）的节点都没有正常的心跳回应，那么Eureka server就会开启自我保护机制
    renewal-percent-threshold: 0.85