
server:
  # 本服务的端口号
  port: 8080

spring:
  application:
    # 服务名称，在微服务架构中具有唯一性，使用服务名可以找到对应的服务
    name: msc-consumer

eureka:
  client:
    # 消费者需要向eureka server注册，以后Gateway要向server拉取消费者实例
    register-with-eureka: true
    service-url:
      # 消费者需要向eureka server获取生产者地址，多个之间使用【,】隔开
      defaultZone: http://eureka01:7001/eureka/


